Funkacja;
CREATE FUNCTION calcProfit(cost FLOAT, price FLOAT) RETURNS DECIMAL(9,2) BEGIN DECLARE profit DECIMAL(9,2); SET profit = price-cost; RETURN profit; END

Trigger;
CREATE TRIGGER `insertLogi` AFTER INSERT ON `klient` FOR EACH ROW INSERT INTO logs VALUES(null, id,'Inserted',NOW());
CREATE TRIGGER `UPDATEtLogi` AFTER UPDATE ON `klient` FOR EACH ROW INSERT INTO logs VALUES(null, id,'Instert',NOW())

Procedury;
CREATE PROCEDURE `Klient`(IN `tel` INT(11)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN SELECT * FROM klient WHERE Nr_tel = tel; END
CREATE PROCEDURE `Zamowienie`(IN `pro` INT(11)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER BEGIN SELECT * FROM zamowienie WHERE ID_Zamowienie = pro; END
